version: "3.8"

services:
  api01: &api
    image: rinhadebackend:1.1.0
    hostname: api01
    environment:
      - POSTGRES_URI=jdbc:postgresql://db:5432/rinha
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - MQTT_BROKER_URL=tcp://mosquitto:1883
      - MQTT_BROKER_USERNAME=
      - MQTT_BROKER_PASSWORD=
      - MQTT_TOPIC=payments.processing.api01
      - MQTT_CLIENT_GROUP_ID=payment-processor-api01
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
      mosquitto:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "95MB"
    networks:
      - backend
      - payment-processor

  api02:
    <<: *api
    hostname: api02
    environment:
      - POSTGRES_URI=jdbc:postgresql://db:5432/rinha
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - MQTT_BROKER_URL=tcp://mosquitto:1883
      - MQTT_BROKER_USERNAME=
      - MQTT_BROKER_PASSWORD=
      - MQTT_TOPIC=payments.processing.api02
      - MQTT_CLIENT_GROUP_ID=payment-processor-api02
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "95MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    networks:
      - backend

  mosquitto:
    image: eclipse-mosquitto:2.0
    hostname: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    command: mosquitto -c /mosquitto-no-auth.conf
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    networks:
      - backend

  db:
    image: postgres:15-alpine
    hostname: db
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d rinha -U rinha" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"
    networks:
      - backend

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_logs:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true