version: "3.8"

services:
  api01: &api
    image: rinhadebackend:1.1.0
    hostname: api01
    environment:
      - POSTGRES_URI=jdbc:postgresql://db:5432/rinha
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - NATS_URL=nats://nats:4222
      - NATS_SUBJECT=api01.payments.processing
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
    networks:
      - backend
      - payment-processor

  api02:
    <<: *api
    hostname: api02
    environment:
      - POSTGRES_URI=jdbc:postgresql://db:5432/rinha
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - NATS_URL=nats://nats:4222
      - NATS_SUBJECT=api02.payments.processing
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    networks:
      - backend

  nats:
    image: nats:2-alpine
    container_name: nats
    hostname: nats
    ports:
      - "4222:4222"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "4222" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"
    networks:
      - backend

  db:
    image: postgres:15-alpine
    hostname: db
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d rinha -U rinha" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true