spring:
  application:
    name: rinha-de-backend
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          payment-processor:
            connectTimeout: 2000
            readTimeout: 3000
            loggerLevel: basic
          payment-processor-fallback:
            connectTimeout: 2000
            readTimeout: 3000
            loggerLevel: basic
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    parser:
      ALLOW_COMMENTS: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: production

info:
  build:
    name: '@project.name@'
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

management:
  info.git.mode: simple
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: never

resilience4j:
  circuitbreaker:
    instances:
      payment-processor:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        automaticTransitionFromOpenToHalfOpenEnabled: true
      payment-processor-fallback:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      payment-processor:
        timeoutDuration: 3s
      payment-processor-fallback:
        timeoutDuration: 3s

server:
  shutdown: graceful