spring:
  application:
    name: rinha-de-backend
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          payment-processor:
            connectTimeout: 1000
            readTimeout: 2000
            loggerLevel: none
          payment-processor-fallback:
            connectTimeout: 500
            readTimeout: 1500
            loggerLevel: none
      retry:
        enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    parser:
      ALLOW_COMMENTS: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: production

info:
  build:
    name: '@project.name@'
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

management:
  info.git.mode: simple
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: never

resilience4j:
  circuitbreaker:
    instances:
      payment-processor:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 80
        waitDurationInOpenState: 5s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slowCallRateThreshold: 70
        slowCallDurationThreshold: 1500ms
      payment-processor-fallback:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 95
        waitDurationInOpenState: 2s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slowCallRateThreshold: 85
        slowCallDurationThreshold: 2000ms
  timelimiter:
    instances:
      payment-processor:
        timeoutDuration: 2s
      payment-processor-fallback:
        timeoutDuration: 1500ms

server:
  shutdown: graceful