spring:
  datasource:
    url: ${POSTGRES_URI}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

nats:
  url: ${NATS_URL:nats://nats:4222}
  subject: ${NATS_SUBJECT:payments.processing}

external-api:
  payment-processor:
    url: ${PAYMENT_PROCESSOR_DEFAULT_URL:http://payment-processor-default:8080}
  payment-processor-fallback:
    url: ${PAYMENT_PROCESSOR_FALLBACK_URL:http://payment-processor-fallback:8080}