spring:
  application:
    name: rinha-de-backend
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          payment-processor:
            connectTimeout: 500
            readTimeout: 1000
            loggerLevel: none
          payment-processor-fallback:
            connectTimeout: 500
            readTimeout: 1000
            loggerLevel: none
      retry:
        enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    parser:
      ALLOW_COMMENTS: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: production

info:
  build:
    name: '@project.name@'
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

management:
  info.git.mode: simple
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: never

resilience4j:
  circuitbreaker:
    instances:
      payment-processor:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 60
        waitDurationInOpenState: 2s
        automaticTransitionFromOpenToHalfOpenEnabled: true
      payment-processor-fallback:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 60
        waitDurationInOpenState: 2s
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      payment-processor:
        timeoutDuration: 1s
      payment-processor-fallback:
        timeoutDuration: 1s

server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200
      min-spare: 20
    connection-timeout: 5s
    max-connections: 8192
    accept-count: 100