spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rinha
    username: admin
    password: admin
  jpa:
    hibernate.ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

external-api:
  payment-processor:
    url: http://payment-processor-default:8080
  payment-processor-fallback:
    url: http://payment-processor-fallback:8080