spring:
  datasource:
    url: ${POSTGRES_URI}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

payment:
  mqtt:
    broker:
      url: ${MQTT_BROKER_URL}
      username: ${MQTT_BROKER_USERNAME:}
      password: ${MQTT_BROKER_PASSWORD:}
    topic: ${MQTT_TOPIC}
    client:
      group-id: ${MQTT_CLIENT_GROUP_ID}

external-api:
  payment-processor:
    url: ${PAYMENT_PROCESSOR_DEFAULT_URL:http://payment-processor-default:8080}
  payment-processor-fallback:
    url: ${PAYMENT_PROCESSOR_FALLBACK_URL:http://payment-processor-fallback:8080}